name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Build Docker image
      run: |
        docker build -t gcr.io/ddgpt/xxiii-backend .

    - name: Tag Docker image
      run: |
        docker tag $(docker images -q gcr.io/ddgpt/xxiii-backend) gcr.io/ddgpt/xxiii-backend

    - name: Deploy application
      run: |
        bash deploy/deploy.sh
